export const vars = {
  font: {
    sans: "Cambay, sans-serif",
    serif: "Arvo, sans",
    monospace: '"Ubuntu Mono", monospace',
  },
  colors: {
    primary: "peachpuff",
    black: "#000",
    white: "#FFF",
  },
  sizes: {
    small: "8px",
    medium: "16px",
    large: "32px",
  },
  fontSize: {
    xs: "0.75rem",
    sm: "0.875rem",
    base: "1rem",
    lg: "1.125rem",
    xl: "2.25rem",
    "2xl": "1.5rem",
    "3xl": "1.875rem",
    "4xl": "2.25rem",
    "5xl": "3rem",
    "6xl": "4rem",
  },
  fontWeight: {
    hairline: "100",
    thin: "200",
    light: "300",
    normal: "400",
    medium: "500",
    semibold: "600",
    bold: "700",
    extrabold: "800",
    black: "900",
  },
}
