export const vars = {
  font: {
    sans: "Cambay, sans-serif",
    serif: "Arvo, sans",
    monospace: '"Ubuntu Mono", monospace',
  },
  colors: {
    primary: "peachpuff",
    black: "#000",
    white: "#FFF",
  },
  sizes: {
    small: "8px",
    medium: "16px",
    large: "32px",
  },
  fontSize: {
    xs: "0.75rem",
    sm: "0.875rem",
    base: "1rem",
    lg: "1.125rem",
    xl: "2.25rem",
    xxl: "1.5rem",
    xxxl: "1.875rem",
    xxxxl: "2.25rem",
    xxxxxl: "3rem",
    xxxxxxl: "4rem",
  },
  fontWeight: {
    hairline: "100",
    thin: "200",
    light: "300",
    normal: "400",
    medium: "500",
    semibold: "600",
    bold: "700",
    extrabold: "800",
    black: "900",
  },
  breakpoints: {
    tiny: "540px",
    small: "767px",
    medium: "992px",
    large: "1200px",
  },
}
